---

- name: Deploy Nginx App
  hosts: localhost
  gather_facts: false

  tasks:
    - include_vars: ./vars/vars.yaml
    - name: Delete old service if exists
      shell: "minikube kubectl -- delete service nginx"
      args:
        chdir: "{{ ppath }}"
    - name: Delete old deployment if exists
      shell: "minikube kubectl -- delete deployment nginx"
      args:
        chdir: "{{ ppath }}"
    - name: Delete old Image if exists
      shell: "minikube image rm {{image}}"
      args:
        chdir: "{{ ppath }}"
    - name: Load Image
      shell: "minikube image load {{image}}"
      args:
        chdir: "{{ ppath }}"
    - name: Apply Deployment
      shell: minikube kubectl -- apply -f nginx-depl.yaml
      args:
        chdir: "{{ ppath }}"
    - name: Apply Service
      shell: minikube kubectl -- apply -f nginx-service.yaml
      args:
        chdir: "{{ ppath }}"
    - name: Start the Service
      shell: minikube service nginx